// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusActive      AccountStatus = "active"
	AccountStatusDeactivated AccountStatus = "deactivated"
	AccountStatusDeleted     AccountStatus = "deleted"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type IdentityProvider string

const (
	IdentityProviderApple  IdentityProvider = "apple"
	IdentityProviderGoogle IdentityProvider = "google"
)

func (e *IdentityProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityProvider(s)
	case string:
		*e = IdentityProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityProvider: %T", src)
	}
	return nil
}

type NullIdentityProvider struct {
	IdentityProvider IdentityProvider `json:"identity_provider"`
	Valid            bool             `json:"valid"` // Valid is true if IdentityProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityProvider) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityProvider), nil
}

type IntentType string

const (
	IntentTypeCoffee     IntentType = "coffee"
	IntentTypeLunch      IntentType = "lunch"
	IntentTypeNetworking IntentType = "networking"
	IntentTypeMentorship IntentType = "mentorship"
	IntentTypeRideShare  IntentType = "ride_share"
	IntentTypeDating     IntentType = "dating"
)

func (e *IntentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntentType(s)
	case string:
		*e = IntentType(s)
	default:
		return fmt.Errorf("unsupported scan type for IntentType: %T", src)
	}
	return nil
}

type NullIntentType struct {
	IntentType IntentType `json:"intent_type"`
	Valid      bool       `json:"valid"` // Valid is true if IntentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntentType) Scan(value interface{}) error {
	if value == nil {
		ns.IntentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntentType), nil
}

type MeetupRequestStatus string

const (
	MeetupRequestStatusPending   MeetupRequestStatus = "pending"
	MeetupRequestStatusAccepted  MeetupRequestStatus = "accepted"
	MeetupRequestStatusRejected  MeetupRequestStatus = "rejected"
	MeetupRequestStatusWithdrawn MeetupRequestStatus = "withdrawn"
)

func (e *MeetupRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeetupRequestStatus(s)
	case string:
		*e = MeetupRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MeetupRequestStatus: %T", src)
	}
	return nil
}

type NullMeetupRequestStatus struct {
	MeetupRequestStatus MeetupRequestStatus `json:"meetup_request_status"`
	Valid               bool                `json:"valid"` // Valid is true if MeetupRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeetupRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MeetupRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeetupRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeetupRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeetupRequestStatus), nil
}

type MeetupStatus string

const (
	MeetupStatusOpen      MeetupStatus = "open"
	MeetupStatusFull      MeetupStatus = "full"
	MeetupStatusCancelled MeetupStatus = "cancelled"
	MeetupStatusCompleted MeetupStatus = "completed"
)

func (e *MeetupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeetupStatus(s)
	case string:
		*e = MeetupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MeetupStatus: %T", src)
	}
	return nil
}

type NullMeetupStatus struct {
	MeetupStatus MeetupStatus `json:"meetup_status"`
	Valid        bool         `json:"valid"` // Valid is true if MeetupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeetupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MeetupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeetupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeetupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeetupStatus), nil
}

type VerificationPurpose string

const (
	VerificationPurposePhone          VerificationPurpose = "phone"
	VerificationPurposePersonalEmail  VerificationPurpose = "personal_email"
	VerificationPurposeCorporateEmail VerificationPurpose = "corporate_email"
	VerificationPurposeEmailSignup    VerificationPurpose = "email_signup"
)

func (e *VerificationPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationPurpose(s)
	case string:
		*e = VerificationPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationPurpose: %T", src)
	}
	return nil
}

type NullVerificationPurpose struct {
	VerificationPurpose VerificationPurpose `json:"verification_purpose"`
	Valid               bool                `json:"valid"` // Valid is true if VerificationPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationPurpose), nil
}

type DeviceToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	FcmToken  string             `json:"fcm_token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Meetup struct {
	ID            uuid.UUID          `json:"id"`
	HostUserID    uuid.UUID          `json:"host_user_id"`
	Intent        IntentType         `json:"intent"`
	ScheduledFor  pgtype.Timestamptz `json:"scheduled_for"`
	LocationLat   float64            `json:"location_lat"`
	LocationLng   float64            `json:"location_lng"`
	LocationLabel string             `json:"location_label"`
	Capacity      int16              `json:"capacity"`
	Status        MeetupStatus       `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
}

type MeetupFeedback struct {
	MeetupID        uuid.UUID          `json:"meetup_id"`
	UserID          uuid.UUID          `json:"user_id"`
	Happened        bool               `json:"happened"`
	FeltSafe        pgtype.Bool        `json:"felt_safe"`
	ProfileAccurate pgtype.Bool        `json:"profile_accurate"`
	WouldMeetAgain  pgtype.Bool        `json:"would_meet_again"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
}

type MeetupRating struct {
	ID          uuid.UUID          `json:"id"`
	MeetupID    uuid.UUID          `json:"meetup_id"`
	RaterUserID uuid.UUID          `json:"rater_user_id"`
	RatedUserID uuid.UUID          `json:"rated_user_id"`
	Score       int16              `json:"score"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MeetupRequest struct {
	ID           uuid.UUID           `json:"id"`
	MeetupID     uuid.UUID           `json:"meetup_id"`
	RequesterID  uuid.UUID           `json:"requester_id"`
	Status       MeetupRequestStatus `json:"status"`
	AutoRejected bool                `json:"auto_rejected"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz  `json:"resolved_at"`
}

type MeetupSafetyState struct {
	MeetupID          uuid.UUID          `json:"meetup_id"`
	ChecklistAckAt    pgtype.Timestamptz `json:"checklist_ack_at"`
	LiveLocationOptIn bool               `json:"live_location_opt_in"`
	CheckedInAt       pgtype.Timestamptz `json:"checked_in_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	LinkedinSub         pgtype.Text        `json:"linkedin_sub"`
	FullName            string             `json:"full_name"`
	ProfilePhotoUrl     pgtype.Text        `json:"profile_photo_url"`
	Headline            pgtype.Text        `json:"headline"`
	TrustLevel          int16              `json:"trust_level"`
	AccountStatus       AccountStatus      `json:"account_status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PhoneNumber         pgtype.Text        `json:"phone_number"`
	PersonalEmail       pgtype.Text        `json:"personal_email"`
	LegalName           pgtype.Text        `json:"legal_name"`
	Address             pgtype.Text        `json:"address"`
	CompanyDomain       pgtype.Text        `json:"company_domain"`
	WorkEmailVerified   bool               `json:"work_email_verified"`
	WorkEmailVerifiedAt pgtype.Timestamptz `json:"work_email_verified_at"`
	AgeConfirmedOver18  bool               `json:"age_confirmed_over_18"`
	AgeConfirmedAt      pgtype.Timestamptz `json:"age_confirmed_at"`
	PasswordHash        pgtype.Text        `json:"password_hash"`
	RatingAverage       pgtype.Numeric     `json:"rating_average"`
	RatingCount         int32              `json:"rating_count"`
}

type UserIdentity struct {
	ID       uuid.UUID          `json:"id"`
	UserID   uuid.UUID          `json:"user_id"`
	Provider IdentityProvider   `json:"provider"`
	Subject  string             `json:"subject"`
	Email    pgtype.Text        `json:"email"`
	LinkedAt pgtype.Timestamptz `json:"linked_at"`
}

type VerificationCode struct {
	ID        uuid.UUID           `json:"id"`
	UserID    pgtype.UUID         `json:"user_id"`
	Purpose   VerificationPurpose `json:"purpose"`
	Target    string              `json:"target"`
	CodeHash  string              `json:"code_hash"`
	Attempts  int16               `json:"attempts"`
	ExpiresAt pgtype.Timestamptz  `json:"expires_at"`
	CreatedAt pgtype.Timestamptz  `json:"created_at"`
}
