// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteVerificationCode(ctx context.Context, arg DeleteVerificationCodeParams) error
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLinkedInSub(ctx context.Context, linkedinSub pgtype.Text) (User, error)
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error)
	IncrementVerificationAttempts(ctx context.Context, arg IncrementVerificationAttemptsParams) (VerificationCode, error)
	MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error
	UpdateUserPersonalDetails(ctx context.Context, arg UpdateUserPersonalDetailsParams) (User, error)
	UpdateUserPersonalEmail(ctx context.Context, arg UpdateUserPersonalEmailParams) (User, error)
	// Level 2/3 verification (ADR-012, backend/PLAN.md's matching addendum).
	// Each mutation also writes trust_level in the same statement — the caller
	// (internal/service) computes the new value via computeTrustLevel before
	// calling these, so the row is never left with a stale trust_level between
	// the field write and a separate recompute step.
	UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) (User, error)
	UpdateUserWorkEmailVerified(ctx context.Context, arg UpdateUserWorkEmailVerifiedParams) (User, error)
	// One pending code per (user_id, purpose) — a resend overwrites the
	// existing row (including resetting attempts and created_at) rather than
	// stacking a second one.
	UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (VerificationCode, error)
}

var _ Querier = (*Queries)(nil)
