// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (linkedin_sub, full_name, profile_photo_url, headline, trust_level)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at
`

type CreateUserParams struct {
	LinkedinSub     pgtype.Text `json:"linkedin_sub"`
	FullName        string      `json:"full_name"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
	Headline        pgtype.Text `json:"headline"`
	TrustLevel      int16       `json:"trust_level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.LinkedinSub,
		arg.FullName,
		arg.ProfilePhotoUrl,
		arg.Headline,
		arg.TrustLevel,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLinkedInSub = `-- name: GetUserByLinkedInSub :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at FROM users WHERE linkedin_sub = $1
`

func (q *Queries) GetUserByLinkedInSub(ctx context.Context, linkedinSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLinkedInSub, linkedinSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
