// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (linkedin_sub, full_name, profile_photo_url, headline, trust_level)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at
`

type CreateUserParams struct {
	LinkedinSub     pgtype.Text `json:"linkedin_sub"`
	FullName        string      `json:"full_name"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
	Headline        pgtype.Text `json:"headline"`
	TrustLevel      int16       `json:"trust_level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.LinkedinSub,
		arg.FullName,
		arg.ProfilePhotoUrl,
		arg.Headline,
		arg.TrustLevel,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
	)
	return i, err
}

const getUserByLinkedInSub = `-- name: GetUserByLinkedInSub :one
SELECT id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at FROM users WHERE linkedin_sub = $1
`

func (q *Queries) GetUserByLinkedInSub(ctx context.Context, linkedinSub pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLinkedInSub, linkedinSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
	)
	return i, err
}

const updateUserPersonalDetails = `-- name: UpdateUserPersonalDetails :one
UPDATE users SET legal_name = $2, address = $3, trust_level = $4 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at
`

type UpdateUserPersonalDetailsParams struct {
	ID         uuid.UUID   `json:"id"`
	LegalName  pgtype.Text `json:"legal_name"`
	Address    pgtype.Text `json:"address"`
	TrustLevel int16       `json:"trust_level"`
}

func (q *Queries) UpdateUserPersonalDetails(ctx context.Context, arg UpdateUserPersonalDetailsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPersonalDetails,
		arg.ID,
		arg.LegalName,
		arg.Address,
		arg.TrustLevel,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
	)
	return i, err
}

const updateUserPersonalEmail = `-- name: UpdateUserPersonalEmail :one
UPDATE users SET personal_email = $2, trust_level = $3 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at
`

type UpdateUserPersonalEmailParams struct {
	ID            uuid.UUID   `json:"id"`
	PersonalEmail pgtype.Text `json:"personal_email"`
	TrustLevel    int16       `json:"trust_level"`
}

func (q *Queries) UpdateUserPersonalEmail(ctx context.Context, arg UpdateUserPersonalEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPersonalEmail, arg.ID, arg.PersonalEmail, arg.TrustLevel)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
	)
	return i, err
}

const updateUserPhoneNumber = `-- name: UpdateUserPhoneNumber :one

UPDATE users SET phone_number = $2, trust_level = $3 WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at
`

type UpdateUserPhoneNumberParams struct {
	ID          uuid.UUID   `json:"id"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	TrustLevel  int16       `json:"trust_level"`
}

// Level 2/3 verification (ADR-012, backend/PLAN.md's matching addendum).
// Each mutation also writes trust_level in the same statement — the caller
// (internal/service) computes the new value via computeTrustLevel before
// calling these, so the row is never left with a stale trust_level between
// the field write and a separate recompute step.
func (q *Queries) UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPhoneNumber, arg.ID, arg.PhoneNumber, arg.TrustLevel)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
	)
	return i, err
}

const updateUserWorkEmailVerified = `-- name: UpdateUserWorkEmailVerified :one
UPDATE users SET company_domain = $2, work_email_verified = $3, work_email_verified_at = $4, trust_level = $5
WHERE id = $1 RETURNING id, linkedin_sub, full_name, profile_photo_url, headline, trust_level, account_status, created_at, updated_at, phone_number, personal_email, legal_name, address, company_domain, work_email_verified, work_email_verified_at
`

type UpdateUserWorkEmailVerifiedParams struct {
	ID                  uuid.UUID          `json:"id"`
	CompanyDomain       pgtype.Text        `json:"company_domain"`
	WorkEmailVerified   bool               `json:"work_email_verified"`
	WorkEmailVerifiedAt pgtype.Timestamptz `json:"work_email_verified_at"`
	TrustLevel          int16              `json:"trust_level"`
}

func (q *Queries) UpdateUserWorkEmailVerified(ctx context.Context, arg UpdateUserWorkEmailVerifiedParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserWorkEmailVerified,
		arg.ID,
		arg.CompanyDomain,
		arg.WorkEmailVerified,
		arg.WorkEmailVerifiedAt,
		arg.TrustLevel,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LinkedinSub,
		&i.FullName,
		&i.ProfilePhotoUrl,
		&i.Headline,
		&i.TrustLevel,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
		&i.PersonalEmail,
		&i.LegalName,
		&i.Address,
		&i.CompanyDomain,
		&i.WorkEmailVerified,
		&i.WorkEmailVerifiedAt,
	)
	return i, err
}
