// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_codes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVerificationCode = `-- name: DeleteVerificationCode :exec
DELETE FROM verification_codes WHERE user_id = $1 AND purpose = $2
`

type DeleteVerificationCodeParams struct {
	UserID  uuid.UUID           `json:"user_id"`
	Purpose VerificationPurpose `json:"purpose"`
}

func (q *Queries) DeleteVerificationCode(ctx context.Context, arg DeleteVerificationCodeParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationCode, arg.UserID, arg.Purpose)
	return err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, user_id, purpose, target, code_hash, attempts, expires_at, created_at FROM verification_codes WHERE user_id = $1 AND purpose = $2
`

type GetVerificationCodeParams struct {
	UserID  uuid.UUID           `json:"user_id"`
	Purpose VerificationPurpose `json:"purpose"`
}

func (q *Queries) GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCode, arg.UserID, arg.Purpose)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementVerificationAttempts = `-- name: IncrementVerificationAttempts :one
UPDATE verification_codes SET attempts = attempts + 1
WHERE user_id = $1 AND purpose = $2
RETURNING id, user_id, purpose, target, code_hash, attempts, expires_at, created_at
`

type IncrementVerificationAttemptsParams struct {
	UserID  uuid.UUID           `json:"user_id"`
	Purpose VerificationPurpose `json:"purpose"`
}

func (q *Queries) IncrementVerificationAttempts(ctx context.Context, arg IncrementVerificationAttemptsParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, incrementVerificationAttempts, arg.UserID, arg.Purpose)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVerificationCode = `-- name: UpsertVerificationCode :one
INSERT INTO verification_codes (user_id, purpose, target, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, purpose)
DO UPDATE SET target = $3, code_hash = $4, attempts = 0, expires_at = $5, created_at = now()
RETURNING id, user_id, purpose, target, code_hash, attempts, expires_at, created_at
`

type UpsertVerificationCodeParams struct {
	UserID    uuid.UUID           `json:"user_id"`
	Purpose   VerificationPurpose `json:"purpose"`
	Target    string              `json:"target"`
	CodeHash  string              `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz  `json:"expires_at"`
}

// One pending code per (user_id, purpose) — a resend overwrites the
// existing row (including resetting attempts and created_at) rather than
// stacking a second one.
func (q *Queries) UpsertVerificationCode(ctx context.Context, arg UpsertVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, upsertVerificationCode,
		arg.UserID,
		arg.Purpose,
		arg.Target,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Target,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
