// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentityProviderProto — LINKEDIN is valid for LinkIdentityRequest (the
// Profile "Connect LinkedIn" flow) but never for CompleteFederatedSignup,
// which only ever accepts APPLE/GOOGLE (LinkedIn's own direct-signup path
// is CompleteLinkedInOnboarding, unchanged from ADR-011, not this RPC).
type IdentityProviderProto int32

const (
	IdentityProviderProto_IDENTITY_PROVIDER_UNSPECIFIED IdentityProviderProto = 0
	IdentityProviderProto_IDENTITY_PROVIDER_APPLE       IdentityProviderProto = 1
	IdentityProviderProto_IDENTITY_PROVIDER_GOOGLE      IdentityProviderProto = 2
	IdentityProviderProto_IDENTITY_PROVIDER_LINKEDIN    IdentityProviderProto = 3
)

// Enum value maps for IdentityProviderProto.
var (
	IdentityProviderProto_name = map[int32]string{
		0: "IDENTITY_PROVIDER_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_APPLE",
		2: "IDENTITY_PROVIDER_GOOGLE",
		3: "IDENTITY_PROVIDER_LINKEDIN",
	}
	IdentityProviderProto_value = map[string]int32{
		"IDENTITY_PROVIDER_UNSPECIFIED": 0,
		"IDENTITY_PROVIDER_APPLE":       1,
		"IDENTITY_PROVIDER_GOOGLE":      2,
		"IDENTITY_PROVIDER_LINKEDIN":    3,
	}
)

func (x IdentityProviderProto) Enum() *IdentityProviderProto {
	p := new(IdentityProviderProto)
	*p = x
	return p
}

func (x IdentityProviderProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProviderProto) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (IdentityProviderProto) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[0]
}

func (x IdentityProviderProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityProviderProto.Descriptor instead.
func (IdentityProviderProto) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

// VerificationPurpose is shared across phone/personal-email/corporate-email
// — one OTP mechanism, three purposes (backend/PLAN.md's addendum, Step
// C/D), not three separate mechanisms. Redundant with which RPC is called
// (StartPhoneVerification vs. StartPersonalEmailVerification, etc.) by
// design — the service layer asserts the two agree, catching a
// mismatched-purpose client bug rather than silently trusting the RPC
// choice alone.
type VerificationPurpose int32

const (
	VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED     VerificationPurpose = 0
	VerificationPurpose_VERIFICATION_PURPOSE_PHONE           VerificationPurpose = 1
	VerificationPurpose_VERIFICATION_PURPOSE_PERSONAL_EMAIL  VerificationPurpose = 2
	VerificationPurpose_VERIFICATION_PURPOSE_CORPORATE_EMAIL VerificationPurpose = 3
	// Email+password signup (ADR-014 decision #2) — StartEmailSignup is
	// unauthenticated, so StartVerificationRequest.user_id is always "" for
	// this purpose; the service layer routes it to the target-keyed
	// verification_codes methods instead (migration 0004), not the
	// userID-keyed ones the other three purposes use.
	VerificationPurpose_VERIFICATION_PURPOSE_EMAIL_SIGNUP VerificationPurpose = 4
)

// Enum value maps for VerificationPurpose.
var (
	VerificationPurpose_name = map[int32]string{
		0: "VERIFICATION_PURPOSE_UNSPECIFIED",
		1: "VERIFICATION_PURPOSE_PHONE",
		2: "VERIFICATION_PURPOSE_PERSONAL_EMAIL",
		3: "VERIFICATION_PURPOSE_CORPORATE_EMAIL",
		4: "VERIFICATION_PURPOSE_EMAIL_SIGNUP",
	}
	VerificationPurpose_value = map[string]int32{
		"VERIFICATION_PURPOSE_UNSPECIFIED":     0,
		"VERIFICATION_PURPOSE_PHONE":           1,
		"VERIFICATION_PURPOSE_PERSONAL_EMAIL":  2,
		"VERIFICATION_PURPOSE_CORPORATE_EMAIL": 3,
		"VERIFICATION_PURPOSE_EMAIL_SIGNUP":    4,
	}
)

func (x VerificationPurpose) Enum() *VerificationPurpose {
	p := new(VerificationPurpose)
	*p = x
	return p
}

func (x VerificationPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auth_proto_enumTypes[1].Descriptor()
}

func (VerificationPurpose) Type() protoreflect.EnumType {
	return &file_auth_v1_auth_proto_enumTypes[1]
}

func (x VerificationPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationPurpose.Descriptor instead.
func (VerificationPurpose) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

type CompleteFederatedSignupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Provider            IdentityProviderProto  `protobuf:"varint,1,opt,name=provider,proto3,enum=auth.v1.IdentityProviderProto" json:"provider,omitempty"`
	IdToken             string                 `protobuf:"bytes,2,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	AgeConfirmedOver_18 bool                   `protobuf:"varint,3,opt,name=age_confirmed_over_18,json=ageConfirmedOver18,proto3" json:"age_confirmed_over_18,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteFederatedSignupRequest) Reset() {
	*x = CompleteFederatedSignupRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFederatedSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFederatedSignupRequest) ProtoMessage() {}

func (x *CompleteFederatedSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFederatedSignupRequest.ProtoReflect.Descriptor instead.
func (*CompleteFederatedSignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteFederatedSignupRequest) GetProvider() IdentityProviderProto {
	if x != nil {
		return x.Provider
	}
	return IdentityProviderProto_IDENTITY_PROVIDER_UNSPECIFIED
}

func (x *CompleteFederatedSignupRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *CompleteFederatedSignupRequest) GetAgeConfirmedOver_18() bool {
	if x != nil {
		return x.AgeConfirmedOver_18
	}
	return false
}

type CompleteLinkedInOnboardingRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationCode   string                 `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	RedirectUri         string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"` // must exactly match the URI used to start the flow
	AgeConfirmedOver_18 bool                   `protobuf:"varint,3,opt,name=age_confirmed_over_18,json=ageConfirmedOver18,proto3" json:"age_confirmed_over_18,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteLinkedInOnboardingRequest) Reset() {
	*x = CompleteLinkedInOnboardingRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLinkedInOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLinkedInOnboardingRequest) ProtoMessage() {}

func (x *CompleteLinkedInOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLinkedInOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteLinkedInOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteLinkedInOnboardingRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *CompleteLinkedInOnboardingRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *CompleteLinkedInOnboardingRequest) GetAgeConfirmedOver_18() bool {
	if x != nil {
		return x.AgeConfirmedOver_18
	}
	return false
}

type LinkIdentityRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by gateway from verified JWT
	Provider IdentityProviderProto  `protobuf:"varint,2,opt,name=provider,proto3,enum=auth.v1.IdentityProviderProto" json:"provider,omitempty"`
	IdToken  string                 `protobuf:"bytes,3,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"` // Apple/Google branch: native-SDK id_token, verified via internal/identity
	// LinkedIn branch: its flow is authorization-code, not a native-SDK
	// id_token like Apple/Google, so it needs its own pair of fields on this
	// one generic message rather than a second RPC.
	AuthorizationCode string `protobuf:"bytes,4,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	RedirectUri       string `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"` // must exactly match the URI used to start the flow
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LinkIdentityRequest) Reset() {
	*x = LinkIdentityRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkIdentityRequest) ProtoMessage() {}

func (x *LinkIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkIdentityRequest.ProtoReflect.Descriptor instead.
func (*LinkIdentityRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LinkIdentityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LinkIdentityRequest) GetProvider() IdentityProviderProto {
	if x != nil {
		return x.Provider
	}
	return IdentityProviderProto_IDENTITY_PROVIDER_UNSPECIFIED
}

func (x *LinkIdentityRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *LinkIdentityRequest) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

func (x *LinkIdentityRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type CompleteEmailSignupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Email               string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // the OTP just verified via StartEmailSignup
	Password            string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // hashed server-side (argon2id) before storage, never logged
	AgeConfirmedOver_18 bool                   `protobuf:"varint,4,opt,name=age_confirmed_over_18,json=ageConfirmedOver18,proto3" json:"age_confirmed_over_18,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteEmailSignupRequest) Reset() {
	*x = CompleteEmailSignupRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteEmailSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteEmailSignupRequest) ProtoMessage() {}

func (x *CompleteEmailSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteEmailSignupRequest.ProtoReflect.Descriptor instead.
func (*CompleteEmailSignupRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteEmailSignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CompleteEmailSignupRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CompleteEmailSignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CompleteEmailSignupRequest) GetAgeConfirmedOver_18() bool {
	if x != nil {
		return x.AgeConfirmedOver_18
	}
	return false
}

type LoginWithPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithPasswordRequest) Reset() {
	*x = LoginWithPasswordRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithPasswordRequest) ProtoMessage() {}

func (x *LoginWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginWithPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SessionResponse struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	UserId                      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessToken                 string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken                string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresInSeconds int64                  `protobuf:"varint,4,opt,name=access_token_expires_in_seconds,json=accessTokenExpiresInSeconds,proto3" json:"access_token_expires_in_seconds,omitempty"`
	IsNewUser                   bool                   `protobuf:"varint,5,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	// full_name and profile_photo_url are the values captured from LinkedIn's
	// userinfo response at account creation (see internal/service's
	// CompleteLinkedInOnboarding) and already persisted on the user row —
	// returned here because there is no separate GET /v1/users/me endpoint
	// yet for a client to fetch them from afterward.
	FullName        string `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ProfilePhotoUrl string `protobuf:"bytes,7,opt,name=profile_photo_url,json=profilePhotoUrl,proto3" json:"profile_photo_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionResponse) GetAccessTokenExpiresInSeconds() int64 {
	if x != nil {
		return x.AccessTokenExpiresInSeconds
	}
	return 0
}

func (x *SessionResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

func (x *SessionResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SessionResponse) GetProfilePhotoUrl() string {
	if x != nil {
		return x.ProfilePhotoUrl
	}
	return ""
}

type RefreshSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT, never client-supplied
	Purpose       VerificationPurpose    `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.VerificationPurpose" json:"purpose,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // phone number (E.164) or email address to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVerificationRequest) Reset() {
	*x = StartVerificationRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVerificationRequest) ProtoMessage() {}

func (x *StartVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVerificationRequest.ProtoReflect.Descriptor instead.
func (*StartVerificationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *StartVerificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartVerificationRequest) GetPurpose() VerificationPurpose {
	if x != nil {
		return x.Purpose
	}
	return VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED
}

func (x *StartVerificationRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// Intentionally near-empty — never echoes the code, or any indication of
// whether target already exists on another account (a user-enumeration
// leak). See backend/ARCHITECTURE.md for the full error-mapping rationale.
type StartVerificationResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResendAfterSeconds int32                  `protobuf:"varint,1,opt,name=resend_after_seconds,json=resendAfterSeconds,proto3" json:"resend_after_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StartVerificationResponse) Reset() {
	*x = StartVerificationResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVerificationResponse) ProtoMessage() {}

func (x *StartVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVerificationResponse.ProtoReflect.Descriptor instead.
func (*StartVerificationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *StartVerificationResponse) GetResendAfterSeconds() int32 {
	if x != nil {
		return x.ResendAfterSeconds
	}
	return 0
}

type VerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose       VerificationPurpose    `protobuf:"varint,2,opt,name=purpose,proto3,enum=auth.v1.VerificationPurpose" json:"purpose,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // must match what StartVerification was called with
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyCodeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyCodeRequest) GetPurpose() VerificationPurpose {
	if x != nil {
		return x.Purpose
	}
	return VerificationPurpose_VERIFICATION_PURPOSE_UNSPECIFIED
}

func (x *VerifyCodeRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VerifyCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SubmitPersonalDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LegalName     string                 `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPersonalDetailsRequest) Reset() {
	*x = SubmitPersonalDetailsRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPersonalDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPersonalDetailsRequest) ProtoMessage() {}

func (x *SubmitPersonalDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPersonalDetailsRequest.ProtoReflect.Descriptor instead.
func (*SubmitPersonalDetailsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitPersonalDetailsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitPersonalDetailsRequest) GetLegalName() string {
	if x != nil {
		return x.LegalName
	}
	return ""
}

func (x *SubmitPersonalDetailsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // set by the gateway from the verified JWT, never client-supplied
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ProfileResponse never carries a raw phone number or email address —
// booleans/derived fields only (Verification Model § 1's "never reveal a
// user's full phone number" rule, applied here to personal/corporate email
// too). full_name/profile_photo_url are already in SessionResponse but
// repeated here since this is the one endpoint a client can call any time
// to refresh its whole profile view, not just at sign-in.
type ProfileResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	UserId                  string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName                string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ProfilePhotoUrl         string                 `protobuf:"bytes,3,opt,name=profile_photo_url,json=profilePhotoUrl,proto3" json:"profile_photo_url,omitempty"`
	TrustLevel              int32                  `protobuf:"varint,4,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	PhoneVerified           bool                   `protobuf:"varint,5,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	PersonalEmailVerified   bool                   `protobuf:"varint,6,opt,name=personal_email_verified,json=personalEmailVerified,proto3" json:"personal_email_verified,omitempty"`
	PersonalDetailsComplete bool                   `protobuf:"varint,7,opt,name=personal_details_complete,json=personalDetailsComplete,proto3" json:"personal_details_complete,omitempty"`
	CompanyDomain           string                 `protobuf:"bytes,8,opt,name=company_domain,json=companyDomain,proto3" json:"company_domain,omitempty"`
	WorkEmailVerified       bool                   `protobuf:"varint,9,opt,name=work_email_verified,json=workEmailVerified,proto3" json:"work_email_verified,omitempty"`
	// Post-meetup star rating aggregate (ADR-015,
	// docs/02-domain/domain-model.md § Rating) — read here from the same
	// users columns services/meetup writes to after SubmitRating.
	RatingAverage float64 `protobuf:"fixed64,10,opt,name=rating_average,json=ratingAverage,proto3" json:"rating_average,omitempty"`
	RatingCount   int32   `protobuf:"varint,11,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ProfileResponse) GetProfilePhotoUrl() string {
	if x != nil {
		return x.ProfilePhotoUrl
	}
	return ""
}

func (x *ProfileResponse) GetTrustLevel() int32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *ProfileResponse) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *ProfileResponse) GetPersonalEmailVerified() bool {
	if x != nil {
		return x.PersonalEmailVerified
	}
	return false
}

func (x *ProfileResponse) GetPersonalDetailsComplete() bool {
	if x != nil {
		return x.PersonalDetailsComplete
	}
	return false
}

func (x *ProfileResponse) GetCompanyDomain() string {
	if x != nil {
		return x.CompanyDomain
	}
	return ""
}

func (x *ProfileResponse) GetWorkEmailVerified() bool {
	if x != nil {
		return x.WorkEmailVerified
	}
	return false
}

func (x *ProfileResponse) GetRatingAverage() float64 {
	if x != nil {
		return x.RatingAverage
	}
	return 0
}

func (x *ProfileResponse) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\"\xaa\x01\n" +
	"\x1eCompleteFederatedSignupRequest\x12:\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1e.auth.v1.IdentityProviderProtoR\bprovider\x12\x19\n" +
	"\bid_token\x18\x02 \x01(\tR\aidToken\x121\n" +
	"\x15age_confirmed_over_18\x18\x03 \x01(\bR\x12ageConfirmedOver18\"\xbd\x01\n" +
	"!CompleteLinkedInOnboardingRequest\x12-\n" +
	"\x12authorization_code\x18\x01 \x01(\tR\x11authorizationCode\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x121\n" +
	"\x15age_confirmed_over_18\x18\x03 \x01(\bR\x12ageConfirmedOver18J\x04\b\x04\x10\x05R\rpkce_verifier\"\xd7\x01\n" +
	"\x13LinkIdentityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x1e.auth.v1.IdentityProviderProtoR\bprovider\x12\x19\n" +
	"\bid_token\x18\x03 \x01(\tR\aidToken\x12-\n" +
	"\x12authorization_code\x18\x04 \x01(\tR\x11authorizationCode\x12!\n" +
	"\fredirect_uri\x18\x05 \x01(\tR\vredirectUri\"\x95\x01\n" +
	"\x1aCompleteEmailSignupRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x121\n" +
	"\x15age_confirmed_over_18\x18\x04 \x01(\bR\x12ageConfirmedOver18\"L\n" +
	"\x18LoginWithPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xa1\x02\n" +
	"\x0fSessionResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12D\n" +
	"\x1faccess_token_expires_in_seconds\x18\x04 \x01(\x03R\x1baccessTokenExpiresInSeconds\x12\x1e\n" +
	"\vis_new_user\x18\x05 \x01(\bR\tisNewUser\x12\x1b\n" +
	"\tfull_name\x18\x06 \x01(\tR\bfullName\x12*\n" +
	"\x11profile_photo_url\x18\a \x01(\tR\x0fprofilePhotoUrl\"<\n" +
	"\x15RefreshSessionRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\";\n" +
	"\x14RevokeSessionRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x83\x01\n" +
	"\x18StartVerificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1c.auth.v1.VerificationPurposeR\apurpose\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"M\n" +
	"\x19StartVerificationResponse\x120\n" +
	"\x14resend_after_seconds\x18\x01 \x01(\x05R\x12resendAfterSeconds\"\x90\x01\n" +
	"\x11VerifyCodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1c.auth.v1.VerificationPurposeR\apurpose\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"p\n" +
	"\x1cSubmitPersonalDetailsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tR\tlegalName\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xd0\x03\n" +
	"\x0fProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12*\n" +
	"\x11profile_photo_url\x18\x03 \x01(\tR\x0fprofilePhotoUrl\x12\x1f\n" +
	"\vtrust_level\x18\x04 \x01(\x05R\n" +
	"trustLevel\x12%\n" +
	"\x0ephone_verified\x18\x05 \x01(\bR\rphoneVerified\x126\n" +
	"\x17personal_email_verified\x18\x06 \x01(\bR\x15personalEmailVerified\x12:\n" +
	"\x19personal_details_complete\x18\a \x01(\bR\x17personalDetailsComplete\x12%\n" +
	"\x0ecompany_domain\x18\b \x01(\tR\rcompanyDomain\x12.\n" +
	"\x13work_email_verified\x18\t \x01(\bR\x11workEmailVerified\x12%\n" +
	"\x0erating_average\x18\n" +
	" \x01(\x01R\rratingAverage\x12!\n" +
	"\frating_count\x18\v \x01(\x05R\vratingCount*\x95\x01\n" +
	"\x15IdentityProviderProto\x12!\n" +
	"\x1dIDENTITY_PROVIDER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17IDENTITY_PROVIDER_APPLE\x10\x01\x12\x1c\n" +
	"\x18IDENTITY_PROVIDER_GOOGLE\x10\x02\x12\x1e\n" +
	"\x1aIDENTITY_PROVIDER_LINKEDIN\x10\x03*\xd5\x01\n" +
	"\x13VerificationPurpose\x12$\n" +
	" VERIFICATION_PURPOSE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aVERIFICATION_PURPOSE_PHONE\x10\x01\x12'\n" +
	"#VERIFICATION_PURPOSE_PERSONAL_EMAIL\x10\x02\x12(\n" +
	"$VERIFICATION_PURPOSE_CORPORATE_EMAIL\x10\x03\x12%\n" +
	"!VERIFICATION_PURPOSE_EMAIL_SIGNUP\x10\x042\xf4\n" +
	"\n" +
	"\vAuthService\x12\\\n" +
	"\x17CompleteFederatedSignup\x12'.auth.v1.CompleteFederatedSignupRequest\x1a\x18.auth.v1.SessionResponse\x12b\n" +
	"\x1aCompleteLinkedInOnboarding\x12*.auth.v1.CompleteLinkedInOnboardingRequest\x1a\x18.auth.v1.SessionResponse\x12F\n" +
	"\fLinkIdentity\x12\x1c.auth.v1.LinkIdentityRequest\x1a\x18.auth.v1.SessionResponse\x12Y\n" +
	"\x10StartEmailSignup\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12T\n" +
	"\x13CompleteEmailSignup\x12#.auth.v1.CompleteEmailSignupRequest\x1a\x18.auth.v1.SessionResponse\x12P\n" +
	"\x11LoginWithPassword\x12!.auth.v1.LoginWithPasswordRequest\x1a\x18.auth.v1.SessionResponse\x12J\n" +
	"\x0eRefreshSession\x12\x1e.auth.v1.RefreshSessionRequest\x1a\x18.auth.v1.SessionResponse\x12N\n" +
	"\rRevokeSession\x12\x1d.auth.v1.RevokeSessionRequest\x1a\x1e.auth.v1.RevokeSessionResponse\x12_\n" +
	"\x16StartPhoneVerification\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12G\n" +
	"\x0fVerifyPhoneCode\x12\x1a.auth.v1.VerifyCodeRequest\x1a\x18.auth.v1.SessionResponse\x12g\n" +
	"\x1eStartPersonalEmailVerification\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12O\n" +
	"\x17VerifyPersonalEmailCode\x12\x1a.auth.v1.VerifyCodeRequest\x1a\x18.auth.v1.SessionResponse\x12X\n" +
	"\x15SubmitPersonalDetails\x12%.auth.v1.SubmitPersonalDetailsRequest\x1a\x18.auth.v1.SessionResponse\x12h\n" +
	"\x1fStartCorporateEmailVerification\x12!.auth.v1.StartVerificationRequest\x1a\".auth.v1.StartVerificationResponse\x12P\n" +
	"\x18VerifyCorporateEmailCode\x12\x1a.auth.v1.VerifyCodeRequest\x1a\x18.auth.v1.SessionResponse\x12B\n" +
	"\n" +
	"GetProfile\x12\x1a.auth.v1.GetProfileRequest\x1a\x18.auth.v1.ProfileResponseBIZGgithub.com/professional-connections/backend/shared/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_auth_v1_auth_proto_goTypes = []any{
	(IdentityProviderProto)(0),                // 0: auth.v1.IdentityProviderProto
	(VerificationPurpose)(0),                  // 1: auth.v1.VerificationPurpose
	(*CompleteFederatedSignupRequest)(nil),    // 2: auth.v1.CompleteFederatedSignupRequest
	(*CompleteLinkedInOnboardingRequest)(nil), // 3: auth.v1.CompleteLinkedInOnboardingRequest
	(*LinkIdentityRequest)(nil),               // 4: auth.v1.LinkIdentityRequest
	(*CompleteEmailSignupRequest)(nil),        // 5: auth.v1.CompleteEmailSignupRequest
	(*LoginWithPasswordRequest)(nil),          // 6: auth.v1.LoginWithPasswordRequest
	(*SessionResponse)(nil),                   // 7: auth.v1.SessionResponse
	(*RefreshSessionRequest)(nil),             // 8: auth.v1.RefreshSessionRequest
	(*RevokeSessionRequest)(nil),              // 9: auth.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),             // 10: auth.v1.RevokeSessionResponse
	(*StartVerificationRequest)(nil),          // 11: auth.v1.StartVerificationRequest
	(*StartVerificationResponse)(nil),         // 12: auth.v1.StartVerificationResponse
	(*VerifyCodeRequest)(nil),                 // 13: auth.v1.VerifyCodeRequest
	(*SubmitPersonalDetailsRequest)(nil),      // 14: auth.v1.SubmitPersonalDetailsRequest
	(*GetProfileRequest)(nil),                 // 15: auth.v1.GetProfileRequest
	(*ProfileResponse)(nil),                   // 16: auth.v1.ProfileResponse
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0,  // 0: auth.v1.CompleteFederatedSignupRequest.provider:type_name -> auth.v1.IdentityProviderProto
	0,  // 1: auth.v1.LinkIdentityRequest.provider:type_name -> auth.v1.IdentityProviderProto
	1,  // 2: auth.v1.StartVerificationRequest.purpose:type_name -> auth.v1.VerificationPurpose
	1,  // 3: auth.v1.VerifyCodeRequest.purpose:type_name -> auth.v1.VerificationPurpose
	2,  // 4: auth.v1.AuthService.CompleteFederatedSignup:input_type -> auth.v1.CompleteFederatedSignupRequest
	3,  // 5: auth.v1.AuthService.CompleteLinkedInOnboarding:input_type -> auth.v1.CompleteLinkedInOnboardingRequest
	4,  // 6: auth.v1.AuthService.LinkIdentity:input_type -> auth.v1.LinkIdentityRequest
	11, // 7: auth.v1.AuthService.StartEmailSignup:input_type -> auth.v1.StartVerificationRequest
	5,  // 8: auth.v1.AuthService.CompleteEmailSignup:input_type -> auth.v1.CompleteEmailSignupRequest
	6,  // 9: auth.v1.AuthService.LoginWithPassword:input_type -> auth.v1.LoginWithPasswordRequest
	8,  // 10: auth.v1.AuthService.RefreshSession:input_type -> auth.v1.RefreshSessionRequest
	9,  // 11: auth.v1.AuthService.RevokeSession:input_type -> auth.v1.RevokeSessionRequest
	11, // 12: auth.v1.AuthService.StartPhoneVerification:input_type -> auth.v1.StartVerificationRequest
	13, // 13: auth.v1.AuthService.VerifyPhoneCode:input_type -> auth.v1.VerifyCodeRequest
	11, // 14: auth.v1.AuthService.StartPersonalEmailVerification:input_type -> auth.v1.StartVerificationRequest
	13, // 15: auth.v1.AuthService.VerifyPersonalEmailCode:input_type -> auth.v1.VerifyCodeRequest
	14, // 16: auth.v1.AuthService.SubmitPersonalDetails:input_type -> auth.v1.SubmitPersonalDetailsRequest
	11, // 17: auth.v1.AuthService.StartCorporateEmailVerification:input_type -> auth.v1.StartVerificationRequest
	13, // 18: auth.v1.AuthService.VerifyCorporateEmailCode:input_type -> auth.v1.VerifyCodeRequest
	15, // 19: auth.v1.AuthService.GetProfile:input_type -> auth.v1.GetProfileRequest
	7,  // 20: auth.v1.AuthService.CompleteFederatedSignup:output_type -> auth.v1.SessionResponse
	7,  // 21: auth.v1.AuthService.CompleteLinkedInOnboarding:output_type -> auth.v1.SessionResponse
	7,  // 22: auth.v1.AuthService.LinkIdentity:output_type -> auth.v1.SessionResponse
	12, // 23: auth.v1.AuthService.StartEmailSignup:output_type -> auth.v1.StartVerificationResponse
	7,  // 24: auth.v1.AuthService.CompleteEmailSignup:output_type -> auth.v1.SessionResponse
	7,  // 25: auth.v1.AuthService.LoginWithPassword:output_type -> auth.v1.SessionResponse
	7,  // 26: auth.v1.AuthService.RefreshSession:output_type -> auth.v1.SessionResponse
	10, // 27: auth.v1.AuthService.RevokeSession:output_type -> auth.v1.RevokeSessionResponse
	12, // 28: auth.v1.AuthService.StartPhoneVerification:output_type -> auth.v1.StartVerificationResponse
	7,  // 29: auth.v1.AuthService.VerifyPhoneCode:output_type -> auth.v1.SessionResponse
	12, // 30: auth.v1.AuthService.StartPersonalEmailVerification:output_type -> auth.v1.StartVerificationResponse
	7,  // 31: auth.v1.AuthService.VerifyPersonalEmailCode:output_type -> auth.v1.SessionResponse
	7,  // 32: auth.v1.AuthService.SubmitPersonalDetails:output_type -> auth.v1.SessionResponse
	12, // 33: auth.v1.AuthService.StartCorporateEmailVerification:output_type -> auth.v1.StartVerificationResponse
	7,  // 34: auth.v1.AuthService.VerifyCorporateEmailCode:output_type -> auth.v1.SessionResponse
	16, // 35: auth.v1.AuthService.GetProfile:output_type -> auth.v1.ProfileResponse
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
