// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_CompleteLinkedInOnboarding_FullMethodName      = "/auth.v1.AuthService/CompleteLinkedInOnboarding"
	AuthService_RefreshSession_FullMethodName                  = "/auth.v1.AuthService/RefreshSession"
	AuthService_RevokeSession_FullMethodName                   = "/auth.v1.AuthService/RevokeSession"
	AuthService_StartPhoneVerification_FullMethodName          = "/auth.v1.AuthService/StartPhoneVerification"
	AuthService_VerifyPhoneCode_FullMethodName                 = "/auth.v1.AuthService/VerifyPhoneCode"
	AuthService_StartPersonalEmailVerification_FullMethodName  = "/auth.v1.AuthService/StartPersonalEmailVerification"
	AuthService_VerifyPersonalEmailCode_FullMethodName         = "/auth.v1.AuthService/VerifyPersonalEmailCode"
	AuthService_SubmitPersonalDetails_FullMethodName           = "/auth.v1.AuthService/SubmitPersonalDetails"
	AuthService_StartCorporateEmailVerification_FullMethodName = "/auth.v1.AuthService/StartCorporateEmailVerification"
	AuthService_VerifyCorporateEmailCode_FullMethodName        = "/auth.v1.AuthService/VerifyCorporateEmailCode"
	AuthService_GetProfile_FullMethodName                      = "/auth.v1.AuthService/GetProfile"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService is called only by the gateway, over gRPC, inside the private
// Cloud Run network (ADR-008). It is never exposed directly to clients — the
// gateway translates the public REST API into these calls. See
// backend/PLAN.md for the REST contract the gateway exposes.
type AuthServiceClient interface {
	// Exchanges a LinkedIn OIDC authorization code for a Professional
	// Connections session. Creates the user record on first login.
	//
	// Deliberately no PKCE code_verifier here despite ADR-011 originally
	// specifying one: LinkedIn's Sign In with LinkedIn / OpenID Connect
	// product rejects the token exchange outright when code_challenge/
	// code_verifier are present (confirmed via manual curl testing against
	// LinkedIn's real endpoint — identical requests succeed with PKCE
	// omitted, fail with 401 invalid_client when included; LinkedIn's own
	// /oauth/v2/accessToken docs don't list code_verifier as a supported
	// parameter for this product either). Security is still sound without
	// it: this is a confidential client — the LinkedIn client_secret lives
	// only in this service, never in the mobile app — which is what PKCE
	// exists to substitute for on a public client that can't hold a secret.
	CompleteLinkedInOnboarding(ctx context.Context, in *CompleteLinkedInOnboardingRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	// Rotates a refresh token for a new access/refresh token pair. The
	// presented refresh token is invalidated as part of this call, whether or
	// not it was already valid — see ADR-009 on rotation-as-theft-detection.
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	// Revokes a refresh token (logout). Idempotent — revoking an
	// already-revoked or unknown token is not an error.
	RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error)
	// Level 2/3 verification (ADR-012, backend/PLAN.md's matching addendum).
	// Every RPC below requires an authenticated caller — the gateway extracts
	// user_id from the verified JWT and sets it explicitly on the request; a
	// client never supplies its own user_id. Verification-completing RPCs
	// return a fresh SessionResponse (new access token reflecting the
	// updated trust_level) rather than a bare success ack, so the caller
	// doesn't show a stale trust level until the next natural token refresh.
	StartPhoneVerification(ctx context.Context, in *StartVerificationRequest, opts ...grpc.CallOption) (*StartVerificationResponse, error)
	VerifyPhoneCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	StartPersonalEmailVerification(ctx context.Context, in *StartVerificationRequest, opts ...grpc.CallOption) (*StartVerificationResponse, error)
	VerifyPersonalEmailCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	SubmitPersonalDetails(ctx context.Context, in *SubmitPersonalDetailsRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	StartCorporateEmailVerification(ctx context.Context, in *StartVerificationRequest, opts ...grpc.CallOption) (*StartVerificationResponse, error)
	VerifyCorporateEmailCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	// GetProfile returns everything ProfilePage needs to render real
	// verification state — booleans/derived fields only, never a raw phone
	// number or email address (Verification Model § 1's "never reveal a
	// user's full phone number" rule, extended to personal/corporate email
	// here too).
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CompleteLinkedInOnboarding(ctx context.Context, in *CompleteLinkedInOnboardingRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, AuthService_CompleteLinkedInOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, AuthService_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSessionResponse)
	err := c.cc.Invoke(ctx, AuthService_RevokeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartPhoneVerification(ctx context.Context, in *StartVerificationRequest, opts ...grpc.CallOption) (*StartVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVerificationResponse)
	err := c.cc.Invoke(ctx, AuthService_StartPhoneVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyPhoneCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyPhoneCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartPersonalEmailVerification(ctx context.Context, in *StartVerificationRequest, opts ...grpc.CallOption) (*StartVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVerificationResponse)
	err := c.cc.Invoke(ctx, AuthService_StartPersonalEmailVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyPersonalEmailCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyPersonalEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SubmitPersonalDetails(ctx context.Context, in *SubmitPersonalDetailsRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, AuthService_SubmitPersonalDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) StartCorporateEmailVerification(ctx context.Context, in *StartVerificationRequest, opts ...grpc.CallOption) (*StartVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVerificationResponse)
	err := c.cc.Invoke(ctx, AuthService_StartCorporateEmailVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyCorporateEmailCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyCorporateEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, AuthService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService is called only by the gateway, over gRPC, inside the private
// Cloud Run network (ADR-008). It is never exposed directly to clients — the
// gateway translates the public REST API into these calls. See
// backend/PLAN.md for the REST contract the gateway exposes.
type AuthServiceServer interface {
	// Exchanges a LinkedIn OIDC authorization code for a Professional
	// Connections session. Creates the user record on first login.
	//
	// Deliberately no PKCE code_verifier here despite ADR-011 originally
	// specifying one: LinkedIn's Sign In with LinkedIn / OpenID Connect
	// product rejects the token exchange outright when code_challenge/
	// code_verifier are present (confirmed via manual curl testing against
	// LinkedIn's real endpoint — identical requests succeed with PKCE
	// omitted, fail with 401 invalid_client when included; LinkedIn's own
	// /oauth/v2/accessToken docs don't list code_verifier as a supported
	// parameter for this product either). Security is still sound without
	// it: this is a confidential client — the LinkedIn client_secret lives
	// only in this service, never in the mobile app — which is what PKCE
	// exists to substitute for on a public client that can't hold a secret.
	CompleteLinkedInOnboarding(context.Context, *CompleteLinkedInOnboardingRequest) (*SessionResponse, error)
	// Rotates a refresh token for a new access/refresh token pair. The
	// presented refresh token is invalidated as part of this call, whether or
	// not it was already valid — see ADR-009 on rotation-as-theft-detection.
	RefreshSession(context.Context, *RefreshSessionRequest) (*SessionResponse, error)
	// Revokes a refresh token (logout). Idempotent — revoking an
	// already-revoked or unknown token is not an error.
	RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error)
	// Level 2/3 verification (ADR-012, backend/PLAN.md's matching addendum).
	// Every RPC below requires an authenticated caller — the gateway extracts
	// user_id from the verified JWT and sets it explicitly on the request; a
	// client never supplies its own user_id. Verification-completing RPCs
	// return a fresh SessionResponse (new access token reflecting the
	// updated trust_level) rather than a bare success ack, so the caller
	// doesn't show a stale trust level until the next natural token refresh.
	StartPhoneVerification(context.Context, *StartVerificationRequest) (*StartVerificationResponse, error)
	VerifyPhoneCode(context.Context, *VerifyCodeRequest) (*SessionResponse, error)
	StartPersonalEmailVerification(context.Context, *StartVerificationRequest) (*StartVerificationResponse, error)
	VerifyPersonalEmailCode(context.Context, *VerifyCodeRequest) (*SessionResponse, error)
	SubmitPersonalDetails(context.Context, *SubmitPersonalDetailsRequest) (*SessionResponse, error)
	StartCorporateEmailVerification(context.Context, *StartVerificationRequest) (*StartVerificationResponse, error)
	VerifyCorporateEmailCode(context.Context, *VerifyCodeRequest) (*SessionResponse, error)
	// GetProfile returns everything ProfilePage needs to render real
	// verification state — booleans/derived fields only, never a raw phone
	// number or email address (Verification Model § 1's "never reveal a
	// user's full phone number" rule, extended to personal/corporate email
	// here too).
	GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) CompleteLinkedInOnboarding(context.Context, *CompleteLinkedInOnboardingRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteLinkedInOnboarding not implemented")
}
func (UnimplementedAuthServiceServer) RefreshSession(context.Context, *RefreshSessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedAuthServiceServer) RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSession not implemented")
}
func (UnimplementedAuthServiceServer) StartPhoneVerification(context.Context, *StartVerificationRequest) (*StartVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPhoneVerification not implemented")
}
func (UnimplementedAuthServiceServer) VerifyPhoneCode(context.Context, *VerifyCodeRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPhoneCode not implemented")
}
func (UnimplementedAuthServiceServer) StartPersonalEmailVerification(context.Context, *StartVerificationRequest) (*StartVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPersonalEmailVerification not implemented")
}
func (UnimplementedAuthServiceServer) VerifyPersonalEmailCode(context.Context, *VerifyCodeRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyPersonalEmailCode not implemented")
}
func (UnimplementedAuthServiceServer) SubmitPersonalDetails(context.Context, *SubmitPersonalDetailsRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPersonalDetails not implemented")
}
func (UnimplementedAuthServiceServer) StartCorporateEmailVerification(context.Context, *StartVerificationRequest) (*StartVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCorporateEmailVerification not implemented")
}
func (UnimplementedAuthServiceServer) VerifyCorporateEmailCode(context.Context, *VerifyCodeRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCorporateEmailCode not implemented")
}
func (UnimplementedAuthServiceServer) GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_CompleteLinkedInOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteLinkedInOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CompleteLinkedInOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CompleteLinkedInOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CompleteLinkedInOnboarding(ctx, req.(*CompleteLinkedInOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RevokeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RevokeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RevokeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RevokeSession(ctx, req.(*RevokeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartPhoneVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartPhoneVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartPhoneVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartPhoneVerification(ctx, req.(*StartVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyPhoneCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyPhoneCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyPhoneCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyPhoneCode(ctx, req.(*VerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartPersonalEmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartPersonalEmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartPersonalEmailVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartPersonalEmailVerification(ctx, req.(*StartVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyPersonalEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyPersonalEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyPersonalEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyPersonalEmailCode(ctx, req.(*VerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SubmitPersonalDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPersonalDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SubmitPersonalDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SubmitPersonalDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SubmitPersonalDetails(ctx, req.(*SubmitPersonalDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_StartCorporateEmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartCorporateEmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartCorporateEmailVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartCorporateEmailVerification(ctx, req.(*StartVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyCorporateEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyCorporateEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyCorporateEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyCorporateEmailCode(ctx, req.(*VerifyCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompleteLinkedInOnboarding",
			Handler:    _AuthService_CompleteLinkedInOnboarding_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _AuthService_RefreshSession_Handler,
		},
		{
			MethodName: "RevokeSession",
			Handler:    _AuthService_RevokeSession_Handler,
		},
		{
			MethodName: "StartPhoneVerification",
			Handler:    _AuthService_StartPhoneVerification_Handler,
		},
		{
			MethodName: "VerifyPhoneCode",
			Handler:    _AuthService_VerifyPhoneCode_Handler,
		},
		{
			MethodName: "StartPersonalEmailVerification",
			Handler:    _AuthService_StartPersonalEmailVerification_Handler,
		},
		{
			MethodName: "VerifyPersonalEmailCode",
			Handler:    _AuthService_VerifyPersonalEmailCode_Handler,
		},
		{
			MethodName: "SubmitPersonalDetails",
			Handler:    _AuthService_SubmitPersonalDetails_Handler,
		},
		{
			MethodName: "StartCorporateEmailVerification",
			Handler:    _AuthService_StartCorporateEmailVerification_Handler,
		},
		{
			MethodName: "VerifyCorporateEmailCode",
			Handler:    _AuthService_VerifyCorporateEmailCode_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _AuthService_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
