// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listDeviceTokensForUser = `-- name: ListDeviceTokensForUser :many
SELECT id, user_id, fcm_token, created_at, updated_at FROM device_tokens WHERE user_id = $1
`

func (q *Queries) ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FcmToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (user_id, fcm_token)
VALUES ($1, $2)
ON CONFLICT (fcm_token) DO UPDATE SET user_id = $1, updated_at = now()
RETURNING id, user_id, fcm_token, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FcmToken string    `json:"fcm_token"`
}

// Upserts by token, not by user — a token identifies one physical device
// install; re-registering it under a different account reassigns
// ownership rather than leaving a stale row.
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.FcmToken)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
