// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetup_requests.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptMeetupRequest = `-- name: AcceptMeetupRequest :one
UPDATE meetup_requests SET status = 'accepted', resolved_at = now()
WHERE id = $1
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at
`

func (q *Queries) AcceptMeetupRequest(ctx context.Context, id uuid.UUID) (MeetupRequest, error) {
	row := q.db.QueryRow(ctx, acceptMeetupRequest, id)
	var i MeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const autoRejectPendingRequestsForMeetup = `-- name: AutoRejectPendingRequestsForMeetup :many
UPDATE meetup_requests SET status = 'rejected', resolved_at = now(), auto_rejected = true
WHERE meetup_id = $1 AND status = 'pending'
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at
`

// Returns the rejected rows so the caller can notify each requester
// (backend/meetup-scheduling-PLAN.md Step E).
func (q *Queries) AutoRejectPendingRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]MeetupRequest, error) {
	rows, err := q.db.Query(ctx, autoRejectPendingRequestsForMeetup, meetupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetupRequest
	for rows.Next() {
		var i MeetupRequest
		if err := rows.Scan(
			&i.ID,
			&i.MeetupID,
			&i.RequesterID,
			&i.Status,
			&i.AutoRejected,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAcceptedRequests = `-- name: CountAcceptedRequests :one
SELECT count(*) FROM meetup_requests WHERE meetup_id = $1 AND status = 'accepted'
`

func (q *Queries) CountAcceptedRequests(ctx context.Context, meetupID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAcceptedRequests, meetupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMeetupRequest = `-- name: CreateMeetupRequest :one
INSERT INTO meetup_requests (meetup_id, requester_id)
VALUES ($1, $2)
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at
`

type CreateMeetupRequestParams struct {
	MeetupID    uuid.UUID `json:"meetup_id"`
	RequesterID uuid.UUID `json:"requester_id"`
}

func (q *Queries) CreateMeetupRequest(ctx context.Context, arg CreateMeetupRequestParams) (MeetupRequest, error) {
	row := q.db.QueryRow(ctx, createMeetupRequest, arg.MeetupID, arg.RequesterID)
	var i MeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getMeetupRequestByID = `-- name: GetMeetupRequestByID :one
SELECT id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at FROM meetup_requests WHERE id = $1
`

// Plain, no join — used inside Accept's transaction where requester
// display info is irrelevant, and as the base row write queries (Accept/
// Reject/Withdraw) RETURNING against. Callers needing display info should
// use GetMeetupRequestWithRequesterInfoByID instead.
func (q *Queries) GetMeetupRequestByID(ctx context.Context, id uuid.UUID) (MeetupRequest, error) {
	row := q.db.QueryRow(ctx, getMeetupRequestByID, id)
	var i MeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getMeetupRequestWithRequesterInfoByID = `-- name: GetMeetupRequestWithRequesterInfoByID :one
SELECT
  r.id, r.meetup_id, r.requester_id, r.status, r.auto_rejected, r.created_at, r.resolved_at,
  u.full_name AS requester_full_name,
  u.profile_photo_url AS requester_profile_photo_url,
  u.trust_level AS requester_trust_level,
  u.rating_average AS requester_rating_average,
  u.rating_count AS requester_rating_count
FROM meetup_requests r
JOIN users u ON u.id = r.requester_id
WHERE r.id = $1
`

type GetMeetupRequestWithRequesterInfoByIDRow struct {
	ID                       uuid.UUID           `json:"id"`
	MeetupID                 uuid.UUID           `json:"meetup_id"`
	RequesterID              uuid.UUID           `json:"requester_id"`
	Status                   MeetupRequestStatus `json:"status"`
	AutoRejected             bool                `json:"auto_rejected"`
	CreatedAt                pgtype.Timestamptz  `json:"created_at"`
	ResolvedAt               pgtype.Timestamptz  `json:"resolved_at"`
	RequesterFullName        string              `json:"requester_full_name"`
	RequesterProfilePhotoUrl pgtype.Text         `json:"requester_profile_photo_url"`
	RequesterTrustLevel      int16               `json:"requester_trust_level"`
	RequesterRatingAverage   pgtype.Numeric      `json:"requester_rating_average"`
	RequesterRatingCount     int32               `json:"requester_rating_count"`
}

func (q *Queries) GetMeetupRequestWithRequesterInfoByID(ctx context.Context, id uuid.UUID) (GetMeetupRequestWithRequesterInfoByIDRow, error) {
	row := q.db.QueryRow(ctx, getMeetupRequestWithRequesterInfoByID, id)
	var i GetMeetupRequestWithRequesterInfoByIDRow
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.RequesterFullName,
		&i.RequesterProfilePhotoUrl,
		&i.RequesterTrustLevel,
		&i.RequesterRatingAverage,
		&i.RequesterRatingCount,
	)
	return i, err
}

const listRequestsForMeetup = `-- name: ListRequestsForMeetup :many
SELECT
  r.id, r.meetup_id, r.requester_id, r.status, r.auto_rejected, r.created_at, r.resolved_at,
  u.full_name AS requester_full_name,
  u.profile_photo_url AS requester_profile_photo_url,
  u.trust_level AS requester_trust_level,
  u.rating_average AS requester_rating_average,
  u.rating_count AS requester_rating_count
FROM meetup_requests r
JOIN users u ON u.id = r.requester_id
WHERE r.meetup_id = $1
ORDER BY r.created_at ASC
`

type ListRequestsForMeetupRow struct {
	ID                       uuid.UUID           `json:"id"`
	MeetupID                 uuid.UUID           `json:"meetup_id"`
	RequesterID              uuid.UUID           `json:"requester_id"`
	Status                   MeetupRequestStatus `json:"status"`
	AutoRejected             bool                `json:"auto_rejected"`
	CreatedAt                pgtype.Timestamptz  `json:"created_at"`
	ResolvedAt               pgtype.Timestamptz  `json:"resolved_at"`
	RequesterFullName        string              `json:"requester_full_name"`
	RequesterProfilePhotoUrl pgtype.Text         `json:"requester_profile_photo_url"`
	RequesterTrustLevel      int16               `json:"requester_trust_level"`
	RequesterRatingAverage   pgtype.Numeric      `json:"requester_rating_average"`
	RequesterRatingCount     int32               `json:"requester_rating_count"`
}

func (q *Queries) ListRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]ListRequestsForMeetupRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForMeetup, meetupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsForMeetupRow
	for rows.Next() {
		var i ListRequestsForMeetupRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetupID,
			&i.RequesterID,
			&i.Status,
			&i.AutoRejected,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.RequesterFullName,
			&i.RequesterProfilePhotoUrl,
			&i.RequesterTrustLevel,
			&i.RequesterRatingAverage,
			&i.RequesterRatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectMeetupRequest = `-- name: RejectMeetupRequest :one
UPDATE meetup_requests SET status = 'rejected', resolved_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at
`

// WHERE status = 'pending' guards against rejecting an already-resolved
// request (double-tap, or a race with auto-reject) — zero rows affected
// (pgx.ErrNoRows) is the repository's signal to map to apperror.ErrConflict.
func (q *Queries) RejectMeetupRequest(ctx context.Context, id uuid.UUID) (MeetupRequest, error) {
	row := q.db.QueryRow(ctx, rejectMeetupRequest, id)
	var i MeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const withdrawMeetupRequest = `-- name: WithdrawMeetupRequest :one
UPDATE meetup_requests SET status = 'withdrawn', resolved_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at
`

func (q *Queries) WithdrawMeetupRequest(ctx context.Context, id uuid.UUID) (MeetupRequest, error) {
	row := q.db.QueryRow(ctx, withdrawMeetupRequest, id)
	var i MeetupRequest
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RequesterID,
		&i.Status,
		&i.AutoRejected,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
