// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meetups.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelMeetup = `-- name: CancelMeetup :one
UPDATE meetups SET status = 'cancelled', cancelled_at = now()
WHERE id = $1
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at
`

func (q *Queries) CancelMeetup(ctx context.Context, id uuid.UUID) (Meetup, error) {
	row := q.db.QueryRow(ctx, cancelMeetup, id)
	var i Meetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
	)
	return i, err
}

const closeMeetup = `-- name: CloseMeetup :one
UPDATE meetups
SET status = 'completed', closed_at = now()
WHERE id = $1 AND host_user_id = $2 AND status IN ('open', 'full') AND now() >= window_start
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at
`

type CloseMeetupParams struct {
	ID         uuid.UUID `json:"id"`
	HostUserID uuid.UUID `json:"host_user_id"`
}

// The WHERE clause's four conditions (right meetup, right host, currently
// open-ish, window actually started) are the *entire* authorization and
// precondition check — done in the query itself so there's no window
// between "check" and "act" for a concurrent request to slip through
// (ADR-016). Zero rows updated (vs. an error) means one of those four
// failed; the service layer re-fetches to distinguish which for a useful
// error message.
func (q *Queries) CloseMeetup(ctx context.Context, arg CloseMeetupParams) (Meetup, error) {
	row := q.db.QueryRow(ctx, closeMeetup, arg.ID, arg.HostUserID)
	var i Meetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
	)
	return i, err
}

const createMeetup = `-- name: CreateMeetup :one
INSERT INTO meetups (host_user_id, intent, window_start, window_end, location_lat, location_lng, location_label, capacity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at
`

type CreateMeetupParams struct {
	HostUserID    uuid.UUID          `json:"host_user_id"`
	Intent        IntentType         `json:"intent"`
	WindowStart   pgtype.Timestamptz `json:"window_start"`
	WindowEnd     pgtype.Timestamptz `json:"window_end"`
	LocationLat   float64            `json:"location_lat"`
	LocationLng   float64            `json:"location_lng"`
	LocationLabel string             `json:"location_label"`
	Capacity      int16              `json:"capacity"`
}

func (q *Queries) CreateMeetup(ctx context.Context, arg CreateMeetupParams) (Meetup, error) {
	row := q.db.QueryRow(ctx, createMeetup,
		arg.HostUserID,
		arg.Intent,
		arg.WindowStart,
		arg.WindowEnd,
		arg.LocationLat,
		arg.LocationLng,
		arg.LocationLabel,
		arg.Capacity,
	)
	var i Meetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
	)
	return i, err
}

const getMeetupByID = `-- name: GetMeetupByID :one
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at,
  u.full_name AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  u.trust_level AS host_trust_level,
  u.rating_average AS host_rating_average,
  u.rating_count AS host_rating_count,
  (SELECT count(*) FROM meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
  r.status AS my_request_status
FROM meetups m
JOIN users u ON u.id = m.host_user_id
LEFT JOIN meetup_requests r ON r.meetup_id = m.id AND r.requester_id = $2
WHERE m.id = $1
ORDER BY r.created_at DESC NULLS LAST
LIMIT 1
`

type GetMeetupByIDParams struct {
	ID          uuid.UUID `json:"id"`
	RequesterID uuid.UUID `json:"requester_id"`
}

type GetMeetupByIDRow struct {
	ID                  uuid.UUID               `json:"id"`
	HostUserID          uuid.UUID               `json:"host_user_id"`
	Intent              IntentType              `json:"intent"`
	LocationLat         float64                 `json:"location_lat"`
	LocationLng         float64                 `json:"location_lng"`
	LocationLabel       string                  `json:"location_label"`
	Capacity            int16                   `json:"capacity"`
	Status              MeetupStatus            `json:"status"`
	CreatedAt           pgtype.Timestamptz      `json:"created_at"`
	CancelledAt         pgtype.Timestamptz      `json:"cancelled_at"`
	WindowStart         pgtype.Timestamptz      `json:"window_start"`
	WindowEnd           pgtype.Timestamptz      `json:"window_end"`
	ClosedAt            pgtype.Timestamptz      `json:"closed_at"`
	HostFullName        string                  `json:"host_full_name"`
	HostProfilePhotoUrl pgtype.Text             `json:"host_profile_photo_url"`
	HostTrustLevel      int16                   `json:"host_trust_level"`
	HostRatingAverage   pgtype.Numeric          `json:"host_rating_average"`
	HostRatingCount     int32                   `json:"host_rating_count"`
	AcceptedCount       int64                   `json:"accepted_count"`
	MyRequestStatus     NullMeetupRequestStatus `json:"my_request_status"`
}

// my_request_status is the *latest* request this specific user (viewerID)
// has made on this meetup, or NULL if they never requested — the frontend
// uses this to render "REQUEST TO JOIN" vs. the request's current status
// (frontend/meetup-scheduling-PLAN.md Step 3). Plain LEFT JOIN + ORDER BY
// ... LIMIT 1, not a scalar subquery or LEFT JOIN LATERAL in the SELECT
// list — sqlc's nullability analysis correctly infers a plain LEFT JOIN
// column as nullable (NullMeetupRequestStatus); both of the other two forms
// were confirmed (by generating each and inspecting the output) to produce
// a non-nullable Go type that would panic scanning a real NULL row — a
// viewer who's never requested to join, the common browsing case.
func (q *Queries) GetMeetupByID(ctx context.Context, arg GetMeetupByIDParams) (GetMeetupByIDRow, error) {
	row := q.db.QueryRow(ctx, getMeetupByID, arg.ID, arg.RequesterID)
	var i GetMeetupByIDRow
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
		&i.HostFullName,
		&i.HostProfilePhotoUrl,
		&i.HostTrustLevel,
		&i.HostRatingAverage,
		&i.HostRatingCount,
		&i.AcceptedCount,
		&i.MyRequestStatus,
	)
	return i, err
}

const getMeetupByIDForUpdate = `-- name: GetMeetupByIDForUpdate :one
SELECT id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at FROM meetups WHERE id = $1 FOR UPDATE
`

// Plain, no join — used only inside AcceptRequest's transaction to lock the
// row and re-check status/capacity, host display info is irrelevant there.
func (q *Queries) GetMeetupByIDForUpdate(ctx context.Context, id uuid.UUID) (Meetup, error) {
	row := q.db.QueryRow(ctx, getMeetupByIDForUpdate, id)
	var i Meetup
	err := row.Scan(
		&i.ID,
		&i.HostUserID,
		&i.Intent,
		&i.LocationLat,
		&i.LocationLng,
		&i.LocationLabel,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.ClosedAt,
	)
	return i, err
}

const listMeetupsByHost = `-- name: ListMeetupsByHost :many
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at,
  u.full_name AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  u.trust_level AS host_trust_level,
  u.rating_average AS host_rating_average,
  u.rating_count AS host_rating_count,
  (SELECT count(*) FROM meetup_requests r WHERE r.meetup_id = m.id AND r.status = 'accepted') AS accepted_count
FROM meetups m
JOIN users u ON u.id = m.host_user_id
WHERE m.host_user_id = $1
ORDER BY m.created_at DESC
`

type ListMeetupsByHostRow struct {
	ID                  uuid.UUID          `json:"id"`
	HostUserID          uuid.UUID          `json:"host_user_id"`
	Intent              IntentType         `json:"intent"`
	LocationLat         float64            `json:"location_lat"`
	LocationLng         float64            `json:"location_lng"`
	LocationLabel       string             `json:"location_label"`
	Capacity            int16              `json:"capacity"`
	Status              MeetupStatus       `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	CancelledAt         pgtype.Timestamptz `json:"cancelled_at"`
	WindowStart         pgtype.Timestamptz `json:"window_start"`
	WindowEnd           pgtype.Timestamptz `json:"window_end"`
	ClosedAt            pgtype.Timestamptz `json:"closed_at"`
	HostFullName        string             `json:"host_full_name"`
	HostProfilePhotoUrl pgtype.Text        `json:"host_profile_photo_url"`
	HostTrustLevel      int16              `json:"host_trust_level"`
	HostRatingAverage   pgtype.Numeric     `json:"host_rating_average"`
	HostRatingCount     int32              `json:"host_rating_count"`
	AcceptedCount       int64              `json:"accepted_count"`
}

func (q *Queries) ListMeetupsByHost(ctx context.Context, hostUserID uuid.UUID) ([]ListMeetupsByHostRow, error) {
	rows, err := q.db.Query(ctx, listMeetupsByHost, hostUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetupsByHostRow
	for rows.Next() {
		var i ListMeetupsByHostRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetupsRequestedByUser = `-- name: ListMeetupsRequestedByUser :many
WITH latest_request AS (
  SELECT DISTINCT ON (meetup_id) id, meetup_id, requester_id, status, auto_rejected, created_at, resolved_at
  FROM meetup_requests
  WHERE meetup_requests.requester_id = $1
  ORDER BY meetup_id, created_at DESC
)
SELECT
  m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at,
  u.full_name AS host_full_name,
  u.profile_photo_url AS host_profile_photo_url,
  u.trust_level AS host_trust_level,
  u.rating_average AS host_rating_average,
  u.rating_count AS host_rating_count,
  (SELECT count(*) FROM meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
  lr.status AS my_request_status,
  lr.auto_rejected AS my_request_auto_rejected
FROM latest_request lr
JOIN meetups m ON m.id = lr.meetup_id
JOIN users u ON u.id = m.host_user_id
ORDER BY m.created_at DESC
`

type ListMeetupsRequestedByUserRow struct {
	ID                    uuid.UUID           `json:"id"`
	HostUserID            uuid.UUID           `json:"host_user_id"`
	Intent                IntentType          `json:"intent"`
	LocationLat           float64             `json:"location_lat"`
	LocationLng           float64             `json:"location_lng"`
	LocationLabel         string              `json:"location_label"`
	Capacity              int16               `json:"capacity"`
	Status                MeetupStatus        `json:"status"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	CancelledAt           pgtype.Timestamptz  `json:"cancelled_at"`
	WindowStart           pgtype.Timestamptz  `json:"window_start"`
	WindowEnd             pgtype.Timestamptz  `json:"window_end"`
	ClosedAt              pgtype.Timestamptz  `json:"closed_at"`
	HostFullName          string              `json:"host_full_name"`
	HostProfilePhotoUrl   pgtype.Text         `json:"host_profile_photo_url"`
	HostTrustLevel        int16               `json:"host_trust_level"`
	HostRatingAverage     pgtype.Numeric      `json:"host_rating_average"`
	HostRatingCount       int32               `json:"host_rating_count"`
	AcceptedCount         int64               `json:"accepted_count"`
	MyRequestStatus       MeetupRequestStatus `json:"my_request_status"`
	MyRequestAutoRejected bool                `json:"my_request_auto_rejected"`
}

// One row per meetup, carrying the requester's *latest* request status for
// it (a requester can have multiple historical rows for the same meetup —
// e.g. rejected, then withdrawn, then a fresh pending one — the UNIQUE
// constraint is per (meetup_id, requester_id, status), not per
// (meetup_id, requester_id) alone).
func (q *Queries) ListMeetupsRequestedByUser(ctx context.Context, requesterID uuid.UUID) ([]ListMeetupsRequestedByUserRow, error) {
	rows, err := q.db.Query(ctx, listMeetupsRequestedByUser, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetupsRequestedByUserRow
	for rows.Next() {
		var i ListMeetupsRequestedByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
			&i.MyRequestStatus,
			&i.MyRequestAutoRejected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMeetupsByIntentAfterCursor = `-- name: ListOpenMeetupsByIntentAfterCursor :many
WITH deduped AS (
  SELECT DISTINCT ON (m.id)
    m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at,
    u.full_name AS host_full_name,
    u.profile_photo_url AS host_profile_photo_url,
    u.trust_level AS host_trust_level,
    u.rating_average AS host_rating_average,
    u.rating_count AS host_rating_count,
    (SELECT count(*) FROM meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
    r.status AS my_request_status
  FROM meetups m
  JOIN users u ON u.id = m.host_user_id
  LEFT JOIN meetup_requests r ON r.meetup_id = m.id AND r.requester_id = $2
  WHERE m.status = 'open' AND m.intent = $1
  ORDER BY m.id, r.created_at DESC NULLS LAST
)
SELECT id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, host_full_name, host_profile_photo_url, host_trust_level, host_rating_average, host_rating_count, accepted_count, my_request_status FROM deduped
WHERE (created_at, id) < ($4::timestamptz, $5::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListOpenMeetupsByIntentAfterCursorParams struct {
	Intent          IntentType         `json:"intent"`
	RequesterID     uuid.UUID          `json:"requester_id"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
}

type ListOpenMeetupsByIntentAfterCursorRow struct {
	ID                  uuid.UUID               `json:"id"`
	HostUserID          uuid.UUID               `json:"host_user_id"`
	Intent              IntentType              `json:"intent"`
	LocationLat         float64                 `json:"location_lat"`
	LocationLng         float64                 `json:"location_lng"`
	LocationLabel       string                  `json:"location_label"`
	Capacity            int16                   `json:"capacity"`
	Status              MeetupStatus            `json:"status"`
	CreatedAt           pgtype.Timestamptz      `json:"created_at"`
	CancelledAt         pgtype.Timestamptz      `json:"cancelled_at"`
	WindowStart         pgtype.Timestamptz      `json:"window_start"`
	WindowEnd           pgtype.Timestamptz      `json:"window_end"`
	ClosedAt            pgtype.Timestamptz      `json:"closed_at"`
	HostFullName        string                  `json:"host_full_name"`
	HostProfilePhotoUrl pgtype.Text             `json:"host_profile_photo_url"`
	HostTrustLevel      int16                   `json:"host_trust_level"`
	HostRatingAverage   pgtype.Numeric          `json:"host_rating_average"`
	HostRatingCount     int32                   `json:"host_rating_count"`
	AcceptedCount       int64                   `json:"accepted_count"`
	MyRequestStatus     NullMeetupRequestStatus `json:"my_request_status"`
}

// Keyset pagination on (created_at, id) — cursorCreatedAt/cursorID are the
// last row of the previous page, so this resumes strictly after it. Row
// comparison (a, b) < (c, d) is a single index-friendly condition, not a
// chain of ORs. Same DISTINCT-then-re-sort shape as the first-page query
// above, for the same reason.
func (q *Queries) ListOpenMeetupsByIntentAfterCursor(ctx context.Context, arg ListOpenMeetupsByIntentAfterCursorParams) ([]ListOpenMeetupsByIntentAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listOpenMeetupsByIntentAfterCursor,
		arg.Intent,
		arg.RequesterID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenMeetupsByIntentAfterCursorRow
	for rows.Next() {
		var i ListOpenMeetupsByIntentAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
			&i.MyRequestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMeetupsByIntentFirstPage = `-- name: ListOpenMeetupsByIntentFirstPage :many
WITH deduped AS (
  SELECT DISTINCT ON (m.id)
    m.id, m.host_user_id, m.intent, m.location_lat, m.location_lng, m.location_label, m.capacity, m.status, m.created_at, m.cancelled_at, m.window_start, m.window_end, m.closed_at,
    u.full_name AS host_full_name,
    u.profile_photo_url AS host_profile_photo_url,
    u.trust_level AS host_trust_level,
    u.rating_average AS host_rating_average,
    u.rating_count AS host_rating_count,
    (SELECT count(*) FROM meetup_requests r2 WHERE r2.meetup_id = m.id AND r2.status = 'accepted') AS accepted_count,
    r.status AS my_request_status
  FROM meetups m
  JOIN users u ON u.id = m.host_user_id
  LEFT JOIN meetup_requests r ON r.meetup_id = m.id AND r.requester_id = $2
  WHERE m.status = 'open' AND m.intent = $1
  ORDER BY m.id, r.created_at DESC NULLS LAST
)
SELECT id, host_user_id, intent, location_lat, location_lng, location_label, capacity, status, created_at, cancelled_at, window_start, window_end, closed_at, host_full_name, host_profile_photo_url, host_trust_level, host_rating_average, host_rating_count, accepted_count, my_request_status FROM deduped
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListOpenMeetupsByIntentFirstPageParams struct {
	Intent      IntentType `json:"intent"`
	RequesterID uuid.UUID  `json:"requester_id"`
	Limit       int32      `json:"limit"`
}

type ListOpenMeetupsByIntentFirstPageRow struct {
	ID                  uuid.UUID               `json:"id"`
	HostUserID          uuid.UUID               `json:"host_user_id"`
	Intent              IntentType              `json:"intent"`
	LocationLat         float64                 `json:"location_lat"`
	LocationLng         float64                 `json:"location_lng"`
	LocationLabel       string                  `json:"location_label"`
	Capacity            int16                   `json:"capacity"`
	Status              MeetupStatus            `json:"status"`
	CreatedAt           pgtype.Timestamptz      `json:"created_at"`
	CancelledAt         pgtype.Timestamptz      `json:"cancelled_at"`
	WindowStart         pgtype.Timestamptz      `json:"window_start"`
	WindowEnd           pgtype.Timestamptz      `json:"window_end"`
	ClosedAt            pgtype.Timestamptz      `json:"closed_at"`
	HostFullName        string                  `json:"host_full_name"`
	HostProfilePhotoUrl pgtype.Text             `json:"host_profile_photo_url"`
	HostTrustLevel      int16                   `json:"host_trust_level"`
	HostRatingAverage   pgtype.Numeric          `json:"host_rating_average"`
	HostRatingCount     int32                   `json:"host_rating_count"`
	AcceptedCount       int64                   `json:"accepted_count"`
	MyRequestStatus     NullMeetupRequestStatus `json:"my_request_status"`
}

// DISTINCT ON (m.id) + a wrapping SELECT to re-sort by recency: DISTINCT ON
// requires its own ORDER BY to start with the same expression(s), which
// would otherwise force sorting this page by id instead of created_at —
// the inner query dedupes (a requester can have multiple historical
// meetup_requests rows for the same meetup, see ListMeetupsRequestedByUser
// above), the outer one restores the intended pagination order. Plain LEFT
// JOIN (not LATERAL/a scalar subquery) for my_request_status, same
// nullability reasoning as GetMeetupByID above.
func (q *Queries) ListOpenMeetupsByIntentFirstPage(ctx context.Context, arg ListOpenMeetupsByIntentFirstPageParams) ([]ListOpenMeetupsByIntentFirstPageRow, error) {
	rows, err := q.db.Query(ctx, listOpenMeetupsByIntentFirstPage, arg.Intent, arg.RequesterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenMeetupsByIntentFirstPageRow
	for rows.Next() {
		var i ListOpenMeetupsByIntentFirstPageRow
		if err := rows.Scan(
			&i.ID,
			&i.HostUserID,
			&i.Intent,
			&i.LocationLat,
			&i.LocationLng,
			&i.LocationLabel,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.CancelledAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.ClosedAt,
			&i.HostFullName,
			&i.HostProfilePhotoUrl,
			&i.HostTrustLevel,
			&i.HostRatingAverage,
			&i.HostRatingCount,
			&i.AcceptedCount,
			&i.MyRequestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMeetupFull = `-- name: MarkMeetupFull :exec
UPDATE meetups SET status = 'full' WHERE id = $1
`

func (q *Queries) MarkMeetupFull(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMeetupFull, id)
	return err
}
