// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptMeetupRequest(ctx context.Context, id uuid.UUID) (MeetupRequest, error)
	// Returns the rejected rows so the caller can notify each requester
	// (backend/meetup-scheduling-PLAN.md Step E).
	AutoRejectPendingRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]MeetupRequest, error)
	CancelMeetup(ctx context.Context, id uuid.UUID) (Meetup, error)
	// The WHERE clause's four conditions (right meetup, right host, currently
	// open-ish, window actually started) are the *entire* authorization and
	// precondition check — done in the query itself so there's no window
	// between "check" and "act" for a concurrent request to slip through
	// (ADR-016). Zero rows updated (vs. an error) means one of those four
	// failed; the service layer re-fetches to distinguish which for a useful
	// error message.
	CloseMeetup(ctx context.Context, arg CloseMeetupParams) (Meetup, error)
	CountAcceptedRequests(ctx context.Context, meetupID uuid.UUID) (int64, error)
	CreateMeetup(ctx context.Context, arg CreateMeetupParams) (Meetup, error)
	CreateMeetupRating(ctx context.Context, arg CreateMeetupRatingParams) (MeetupRating, error)
	CreateMeetupRequest(ctx context.Context, arg CreateMeetupRequestParams) (MeetupRequest, error)
	// Idempotent create-if-missing — called the moment a meetup gets its first
	// accepted request (ADR-013 § 3). ON CONFLICT DO NOTHING rather than
	// upsert-with-RETURNING since callers always follow this with a plain Get.
	EnsureSafetyState(ctx context.Context, meetupID uuid.UUID) error
	// my_request_status is the *latest* request this specific user (viewerID)
	// has made on this meetup, or NULL if they never requested — the frontend
	// uses this to render "REQUEST TO JOIN" vs. the request's current status
	// (frontend/meetup-scheduling-PLAN.md Step 3). Plain LEFT JOIN + ORDER BY
	// ... LIMIT 1, not a scalar subquery or LEFT JOIN LATERAL in the SELECT
	// list — sqlc's nullability analysis correctly infers a plain LEFT JOIN
	// column as nullable (NullMeetupRequestStatus); both of the other two forms
	// were confirmed (by generating each and inspecting the output) to produce
	// a non-nullable Go type that would panic scanning a real NULL row — a
	// viewer who's never requested to join, the common browsing case.
	GetMeetupByID(ctx context.Context, arg GetMeetupByIDParams) (GetMeetupByIDRow, error)
	// Plain, no join — used only inside AcceptRequest's transaction to lock the
	// row and re-check status/capacity, host display info is irrelevant there.
	GetMeetupByIDForUpdate(ctx context.Context, id uuid.UUID) (Meetup, error)
	// Plain, no join — used inside Accept's transaction where requester
	// display info is irrelevant, and as the base row write queries (Accept/
	// Reject/Withdraw) RETURNING against. Callers needing display info should
	// use GetMeetupRequestWithRequesterInfoByID instead.
	GetMeetupRequestByID(ctx context.Context, id uuid.UUID) (MeetupRequest, error)
	GetMeetupRequestWithRequesterInfoByID(ctx context.Context, id uuid.UUID) (GetMeetupRequestWithRequesterInfoByIDRow, error)
	GetSafetyState(ctx context.Context, meetupID uuid.UUID) (MeetupSafetyState, error)
	// The rating-eligibility gate: the *rater* must have already confirmed
	// (SubmitMeetupFeedback, happened=true) that the meetup happened. The ratee
	// does not need this — a no-show is legitimately ratable by someone who did
	// attend and confirm (ADR-015).
	HasConfirmedMeetupHappened(ctx context.Context, arg HasConfirmedMeetupHappenedParams) (bool, error)
	// True if userID is the host of meetupID, or has an accepted request on it
	// — the "ratable set" (ADR-015, docs/02-domain/domain-model.md § Rating).
	IsMeetupParticipant(ctx context.Context, arg IsMeetupParticipantParams) (bool, error)
	ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error)
	ListMeetupsByHost(ctx context.Context, hostUserID uuid.UUID) ([]ListMeetupsByHostRow, error)
	// One row per meetup, carrying the requester's *latest* request status for
	// it (a requester can have multiple historical rows for the same meetup —
	// e.g. rejected, then withdrawn, then a fresh pending one — the UNIQUE
	// constraint is per (meetup_id, requester_id, status), not per
	// (meetup_id, requester_id) alone).
	ListMeetupsRequestedByUser(ctx context.Context, requesterID uuid.UUID) ([]ListMeetupsRequestedByUserRow, error)
	// Keyset pagination on (created_at, id) — cursorCreatedAt/cursorID are the
	// last row of the previous page, so this resumes strictly after it. Row
	// comparison (a, b) < (c, d) is a single index-friendly condition, not a
	// chain of ORs. Same DISTINCT-then-re-sort shape as the first-page query
	// above, for the same reason.
	ListOpenMeetupsByIntentAfterCursor(ctx context.Context, arg ListOpenMeetupsByIntentAfterCursorParams) ([]ListOpenMeetupsByIntentAfterCursorRow, error)
	// DISTINCT ON (m.id) + a wrapping SELECT to re-sort by recency: DISTINCT ON
	// requires its own ORDER BY to start with the same expression(s), which
	// would otherwise force sorting this page by id instead of created_at —
	// the inner query dedupes (a requester can have multiple historical
	// meetup_requests rows for the same meetup, see ListMeetupsRequestedByUser
	// above), the outer one restores the intended pagination order. Plain LEFT
	// JOIN (not LATERAL/a scalar subquery) for my_request_status, same
	// nullability reasoning as GetMeetupByID above.
	ListOpenMeetupsByIntentFirstPage(ctx context.Context, arg ListOpenMeetupsByIntentFirstPageParams) ([]ListOpenMeetupsByIntentFirstPageRow, error)
	// Host + accepted requesters of meetupID, excluding viewerID, each flagged
	// with whether viewerID has already rated them for this meetup.
	ListRatableParticipants(ctx context.Context, arg ListRatableParticipantsParams) ([]ListRatableParticipantsRow, error)
	ListRequestsForMeetup(ctx context.Context, meetupID uuid.UUID) ([]ListRequestsForMeetupRow, error)
	MarkMeetupFull(ctx context.Context, id uuid.UUID) error
	// Full recompute via AVG()/COUNT() over meetup_ratings, not an incremental
	// running update — self-correcting, avoids drift, and (run inside the same
	// transaction as CreateMeetupRating, after it) the row lock this UPDATE
	// takes on users serializes concurrent raters of the same person correctly
	// (ADR-015).
	RecomputeUserRating(ctx context.Context, id uuid.UUID) error
	// WHERE status = 'pending' guards against rejecting an already-resolved
	// request (double-tap, or a race with auto-reject) — zero rows affected
	// (pgx.ErrNoRows) is the repository's signal to map to apperror.ErrConflict.
	RejectMeetupRequest(ctx context.Context, id uuid.UUID) (MeetupRequest, error)
	SetCheckedIn(ctx context.Context, meetupID uuid.UUID) (MeetupSafetyState, error)
	SetChecklistAck(ctx context.Context, meetupID uuid.UUID) (MeetupSafetyState, error)
	SetLiveLocationOptIn(ctx context.Context, arg SetLiveLocationOptInParams) (MeetupSafetyState, error)
	// Upserts by token, not by user — a token identifies one physical device
	// install; re-registering it under a different account reassigns
	// ownership rather than leaving a stale row.
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error)
	UpsertMeetupFeedback(ctx context.Context, arg UpsertMeetupFeedbackParams) (MeetupFeedback, error)
	WithdrawMeetupRequest(ctx context.Context, id uuid.UUID) (MeetupRequest, error)
}

var _ Querier = (*Queries)(nil)
