// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMeetupRating = `-- name: CreateMeetupRating :one
INSERT INTO meetup_ratings (meetup_id, rater_user_id, rated_user_id, score)
VALUES ($1, $2, $3, $4)
RETURNING id, meetup_id, rater_user_id, rated_user_id, score, created_at
`

type CreateMeetupRatingParams struct {
	MeetupID    uuid.UUID `json:"meetup_id"`
	RaterUserID uuid.UUID `json:"rater_user_id"`
	RatedUserID uuid.UUID `json:"rated_user_id"`
	Score       int16     `json:"score"`
}

func (q *Queries) CreateMeetupRating(ctx context.Context, arg CreateMeetupRatingParams) (MeetupRating, error) {
	row := q.db.QueryRow(ctx, createMeetupRating,
		arg.MeetupID,
		arg.RaterUserID,
		arg.RatedUserID,
		arg.Score,
	)
	var i MeetupRating
	err := row.Scan(
		&i.ID,
		&i.MeetupID,
		&i.RaterUserID,
		&i.RatedUserID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const hasConfirmedMeetupHappened = `-- name: HasConfirmedMeetupHappened :one
SELECT EXISTS(
  SELECT 1 FROM meetup_feedback WHERE meetup_id = $1 AND user_id = $2 AND happened = true
)
`

type HasConfirmedMeetupHappenedParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// The rating-eligibility gate: the *rater* must have already confirmed
// (SubmitMeetupFeedback, happened=true) that the meetup happened. The ratee
// does not need this — a no-show is legitimately ratable by someone who did
// attend and confirm (ADR-015).
func (q *Queries) HasConfirmedMeetupHappened(ctx context.Context, arg HasConfirmedMeetupHappenedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasConfirmedMeetupHappened, arg.MeetupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isMeetupParticipant = `-- name: IsMeetupParticipant :one
SELECT EXISTS(
  SELECT 1 FROM meetups m WHERE m.id = $1 AND m.host_user_id = $2
  UNION
  SELECT 1 FROM meetup_requests r WHERE r.meetup_id = $1 AND r.requester_id = $2 AND r.status = 'accepted'
)
`

type IsMeetupParticipantParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	UserID   uuid.UUID `json:"user_id"`
}

// True if userID is the host of meetupID, or has an accepted request on it
// — the "ratable set" (ADR-015, docs/02-domain/domain-model.md § Rating).
func (q *Queries) IsMeetupParticipant(ctx context.Context, arg IsMeetupParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMeetupParticipant, arg.MeetupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRatableParticipants = `-- name: ListRatableParticipants :many
SELECT
  u.id,
  u.full_name,
  u.profile_photo_url,
  u.trust_level,
  (mr.id IS NOT NULL)::boolean AS already_rated
FROM (
  SELECT m.host_user_id AS user_id FROM meetups m WHERE m.id = $1
  UNION
  SELECT r.requester_id AS user_id FROM meetup_requests r WHERE r.meetup_id = $1 AND r.status = 'accepted'
) participants
JOIN users u ON u.id = participants.user_id
LEFT JOIN meetup_ratings mr
  ON mr.meetup_id = $1 AND mr.rater_user_id = $2 AND mr.rated_user_id = participants.user_id
WHERE participants.user_id <> $2
`

type ListRatableParticipantsParams struct {
	MeetupID uuid.UUID `json:"meetup_id"`
	ViewerID uuid.UUID `json:"viewer_id"`
}

type ListRatableParticipantsRow struct {
	ID              uuid.UUID   `json:"id"`
	FullName        string      `json:"full_name"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
	TrustLevel      int16       `json:"trust_level"`
	AlreadyRated    bool        `json:"already_rated"`
}

// Host + accepted requesters of meetupID, excluding viewerID, each flagged
// with whether viewerID has already rated them for this meetup.
func (q *Queries) ListRatableParticipants(ctx context.Context, arg ListRatableParticipantsParams) ([]ListRatableParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listRatableParticipants, arg.MeetupID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatableParticipantsRow
	for rows.Next() {
		var i ListRatableParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.ProfilePhotoUrl,
			&i.TrustLevel,
			&i.AlreadyRated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeUserRating = `-- name: RecomputeUserRating :exec
UPDATE users
SET rating_count = (SELECT count(*) FROM meetup_ratings mr WHERE mr.rated_user_id = users.id),
    rating_average = (SELECT COALESCE(ROUND(AVG(mr.score), 2), 0) FROM meetup_ratings mr WHERE mr.rated_user_id = users.id)
WHERE users.id = $1
`

// Full recompute via AVG()/COUNT() over meetup_ratings, not an incremental
// running update — self-correcting, avoids drift, and (run inside the same
// transaction as CreateMeetupRating, after it) the row lock this UPDATE
// takes on users serializes concurrent raters of the same person correctly
// (ADR-015).
func (q *Queries) RecomputeUserRating(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recomputeUserRating, id)
	return err
}
