// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: safety_state.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const ensureSafetyState = `-- name: EnsureSafetyState :exec
INSERT INTO meetup_safety_state (meetup_id) VALUES ($1)
ON CONFLICT (meetup_id) DO NOTHING
`

// Idempotent create-if-missing — called the moment a meetup gets its first
// accepted request (ADR-013 § 3). ON CONFLICT DO NOTHING rather than
// upsert-with-RETURNING since callers always follow this with a plain Get.
func (q *Queries) EnsureSafetyState(ctx context.Context, meetupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureSafetyState, meetupID)
	return err
}

const getSafetyState = `-- name: GetSafetyState :one
SELECT meetup_id, checklist_ack_at, live_location_opt_in, checked_in_at, updated_at FROM meetup_safety_state WHERE meetup_id = $1
`

func (q *Queries) GetSafetyState(ctx context.Context, meetupID uuid.UUID) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, getSafetyState, meetupID)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCheckedIn = `-- name: SetCheckedIn :one
UPDATE meetup_safety_state SET checked_in_at = now() WHERE meetup_id = $1
RETURNING meetup_id, checklist_ack_at, live_location_opt_in, checked_in_at, updated_at
`

func (q *Queries) SetCheckedIn(ctx context.Context, meetupID uuid.UUID) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, setCheckedIn, meetupID)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setChecklistAck = `-- name: SetChecklistAck :one
UPDATE meetup_safety_state SET checklist_ack_at = now() WHERE meetup_id = $1
RETURNING meetup_id, checklist_ack_at, live_location_opt_in, checked_in_at, updated_at
`

func (q *Queries) SetChecklistAck(ctx context.Context, meetupID uuid.UUID) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, setChecklistAck, meetupID)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLiveLocationOptIn = `-- name: SetLiveLocationOptIn :one
UPDATE meetup_safety_state SET live_location_opt_in = $2 WHERE meetup_id = $1
RETURNING meetup_id, checklist_ack_at, live_location_opt_in, checked_in_at, updated_at
`

type SetLiveLocationOptInParams struct {
	MeetupID          uuid.UUID `json:"meetup_id"`
	LiveLocationOptIn bool      `json:"live_location_opt_in"`
}

func (q *Queries) SetLiveLocationOptIn(ctx context.Context, arg SetLiveLocationOptInParams) (MeetupSafetyState, error) {
	row := q.db.QueryRow(ctx, setLiveLocationOptIn, arg.MeetupID, arg.LiveLocationOptIn)
	var i MeetupSafetyState
	err := row.Scan(
		&i.MeetupID,
		&i.ChecklistAckAt,
		&i.LiveLocationOptIn,
		&i.CheckedInAt,
		&i.UpdatedAt,
	)
	return i, err
}
